version: '3'
services:
  frontend:
    build: ./front
    ports:
      - 1911:80
    networks:
      - red
    
  
  backend:
    build: ./back
    ports: 
      - 1912:80
    networks:
      - red

  backend1:
    build: ./back
    ports:
      - 1913:80
    networks:
      - red
  
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - red
    depends_on:
      - backend
      - backend1
      - frontend
      - phpmyadmin

      
  db:
    image: mysql:latest 
    environment:
      MYSQL_DATABASE: bolsa
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  
    
    volumes:
       - ./db:/docker-entrypoint-initdb.d

    networks:
      - red

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 1914:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - red
    depends_on:
      - db

networks:
  red:
    driver: bridge
